#cloud-init

runcmd:
{% if swarmhost %}
    - "docker swarm join --token {{cookiecutter.token}} {{cookiecutter.swarmhost}}"
{% else %}
    - "docker swarm init"
{% endif %}
    - "pip install -y -r requirements.txt"
    - "install tasks.py /home/{{cookiecutter.username}}/tasks.py"
    - "install -d -D /home/{{cookiecutter.username}}/.local/etc/"
    - "install config.yml /home/pirate/.local/etc/config.yml"
