#cloud-init

runcmd:
{% if swarmhost %}
    - "docker swarm join --token {{cookiecutter.token}} {{cookiecutter.swarmhost}}"
{% else %}
    - "docker swarm init"
{% endif %}
    - "pip install -y -r requirements.txt"
    - "cp tasks.py /home/pirate/tasks.py"
    - "mkdir /home/pirate/.local/etc/"
    - "cp config.yml /home/pirate/.local/etc/config.yml"
