# ~/.local/etc/config.yml
## Ansible Playbook - config.yml
## Defines user level configuration and environment
##
## Copyright (C)2021, Da Planet Security. All Rights Reserved
## Licenced under a modified BSD 2.0 Licence.
## Authors:
##   - Dwight Spencer <@denzuko>
# gather_facts: false
# roles:
#    - { role: systemli.drift }
---
- hosts: localhost
  become: true
  vars:
    homedir: "{{ lookup('env', 'HOME') }}"
    pubkey: "{{lookup('env', 'HOME')}}/.ssh/id_rsa.pub"
    gh_token: "{{lookup('env', 'GH_TOKEN')}}"
  tasks:
    - name: Install needed tools
      apt:
        name: "{{item}}"
        update_cache: yes
        state: latest
      loop:
        - monit
        - incron
        - vim-nox
        - mutt
        - fetchmail
        - gpgv2
        - git
        - python3-pip
        - python3-venv
        - python3-jsonschema
        - python3-setuptools
        - httpie
        - msmtp
        - docker
        - irssi
        - surfraw
        - elinks
        - jo
        - jq
        - awscli
        - s3cmd
        - ctags

    - name: remove broken vim
      apt:
        name: vim-tiny
        state: absent

    - name: Configure vimrc
      blockinfile:
        path: "{{homedir}}/.vimrc"
        state: present
        create: yes
        marker: '" {mark} ANSIBLE MANAGED BLOCK'
        content: |
          filetype plugin on
          set nocompatible
          set ts=4 sts=4 sw=4 ai si et tw=80 ff=unix vb
          set ru sb spr ls=2
          set fdm=indent
          set foldlevel=99
          set encoding=utf-8
          set omnifunc=syntaxcomplete#Complete
          syntax on
          set list
          nnoremap <space> za
          augroup Python
            au!
            au BufCreate,BufNewFile,BufRead *.py set tw=79 list rn
            au BufCreate,BufNewFile,BufRead *.py set makeprg=invoke
          augroup end
          augroup yaml
            au!
            au BufNewFile,BufRead *.yaml,*.yml set makeprg=pipx\ run\ yamllint\ %
            au BufNewFile,BufRead *.yaml,*.yml set list ruler rnu
          augroup end

    - name: Configure inputrc
      blockinfile:
          path: "{{homedir}}/.inputrc"
          state: present
          create: yes
          content: |
              set editing-mode vi
              set bell-style none

    - name: Add content for powerline bash lib
      blockinfile:
          path: "{{homedir}}/.local/lib/powerline.sh"
          state: present
          create: yes
          content: |
              powerline-daemon -q
              POWERLINE_BASH_CONTINUATION=1
              POWERLINE_BASH_SELECT=1
              source /usr/share/powerline/bindings/bash/powerline.sh

    - name: append bashrc with powerline lib
      blockinfile:
          path: "{{homedir}}/.bashrc"
          state: present
          create: true
          content: 'source /$HOME/.local/lib/powerline.sh'

    - name: Add vim theme to config directory
      git:
          repo: https://github.com/mr-ubik/vim-hackerman-syntax.git
          force: true
          dest: "{{homedir}}/.vim/"
          depth: 1

    - name: remove theme's git folder [fixme]
      file:
          path: "{{lookup('env', 'HOME') }}/.vim/.git"
          force: true
          state: absent

    - name: establish cron re-provisioning
      cron:
        name: 'rerun config playbook'
        special_time: hourly
        job: "cd {{homedir}}; invoke run_playbook"

    - name: fetchmail periodically
      cron:
        name: 'fetchmail on the hour'
        special_time: hourly
        job: "fetchmail"

    - name: Establish git config, User 
      git_config:
        name: user.name
        scope: global
        value: 'Dwight Spencer'

    - name: Establish git config, Email
      git_config:
        name: user.email
        scope: global
        value: 'dwightaspencer@gmail.com'

    - name: Establish git config, hub protocol
      git_config:
        name: hub.protocol
        scope: global
        value: 'https'

    - name: Establish git config - github user
      git_config:
        name: github.user
        scope: global
        value: 'denzuko'

    - name: Generate an OpenSSH keypair
      openssh_keypair:
          path: "{{homedir}}/.ssh/id_rsa"
          force: yes

    - name: Update github public keys
      github_key:
        name: "Access key - {{ansible_hostname}}"
        token: "{{gh_token}}"
        pubkey: "{{lookup('file', pubkey)}}"

    - name: Add monitrc
      blockinfile:
        path: "{{lookup('env', 'HOME') }}/.bashrc"
        state: present
        create: yes
        content: |
          set daemon 120
          set logfile "{{lookup('env', 'HOME')}}/.monit.log"
          set httpd port 2812 and use address localhost allow localhost allow @adm
          check system localhost if loadavg (1min) > 10 then alert
    - name: theme tmux
      git:
        repo: https://github.com/jimeh/tmux-themepack.git
        dest: "{{homedir}}/.tmux-themepack"

    - name: theme tmux
      git:
        repo: https://github.com/jimeh/tmux-themepack.git
        dest: "{{homedir}}/.tmux-themepack"

    - name: config tmux theme
      blockinfile:
        path: "{{homedir}}/.tmux.conf"
        state: present
        create: yes
        content: |
           source-file "${HOME}/.tmux-themepack/powerline/block/magenta.tmuxtheme"
           unbind C-b
           set-option -g prefix C-a
           bind-key C-a send-prefix
           bind | split-window -h
           bind - split-window -v
           unbind '"'
           unbind %
           set -g mouse-select-window on
           set -g mouse-select-pane on
           set -g mouse-resize-pane on
           set -g mouse on

